### ISSUE TITLE
I could not use mumu.pl to unpack multiple fastq file

### ISSUE THREAD

**Issue by jjlaisnoopy** [KirillKryukov/mumu#8]
Dear KirillKryukov,

     I use the command
      mumu.pl --fastq 'test_R?_001.fastq' > test_pair.mfq
     to pack test_R1_001.fastq and test_R2_001.fastq, it works fine.

    But I could not use mumu.pl to unpack multiple fastq file with the following command,
    mumu.pl --unpack  test_pair.mfq

    Please help me.

**Comment by KirillKryukov** [comment]
Thank you for comment. I noticed that there was no FASTQ unpacking example and other unpacking example commands were wrong.

You need two changes:

1. Unpacking FASTQ format also needs `--fastq` option. (The tool has no autodetection, and does not care about file extension either).

2. Unpacking needs data streamed to standard input.

So, your unpacking command should be changed to:

`mumu.pl --fastq --unpack < test_pair.mfq`

I updated the examples. Thanks!
